---
all:
  vars:
    ansible_connection: ssh
    ansible_port: 22
    ansible_user: "{{ ansible_user }}"
    ansible_password: "{{ ansible_password }}"

  children:
    servers:
      hosts:
        FB-QUAL:
          ansible_host: 192.168.1.46
        FB-QUAL-02:
          ansible_host: 192.168.1.45
