---
- name: Create the group "{{ administrator_group_name }}" on target
  ansible.builtin.group:
    name: "{{ administrator_group_name }}"
    state: present

- name: Add the user "ansible" to the group "{{ administrator_group_name }}"
  ansible.builtin.user:
    name: ansible
    groups:
      - administrators