---
- name : Ping the new server
  ansible.builtin.ping:
  register: ping_result
  ignore_errors: true

- name: Debug si ping échoue
  ansible.builtin.debug:
    msg: "erreur ping"
  when: ping_result is failed

- name: Create admin group on target
  ansible.builtin.group:
    name: administrators
    become: true

- name: Create ansible_user on target
  ansible.builtin.user:
    name: ansible
    groups:
      - administrators
    become: true
